### ISSUE TITLE
Saying hi!

### ISSUE THREAD

**Issue by ericmjl** [jekwatt/effective_python#13]
Hi @jekwatt,

This isn't really an issue, but just me dropping by to say hi! :smile:. I love how you've got this repo up and running to document your learning journey. Hope to catch you around on the virtual interwebs!

Cheers,
Eric

Please feel free to close anytime :)

**Comment by jekwatt** [comment]
Hi @ericmjl,

Thank you for dropping by.  I bought this book a while ago (1st edition) but then recently started reading it again and wanted to document.  I like that each item is self-contained lesson, items are easy to digest and study in whatever order.  

I was looking forward to attending the PyCon sprint.  Hope to see you at another event very soon.

Happy Pythoning!
Jennifer

**Comment by jekwatt** [comment]
Closing.
